version: '3'
services:
  wishlist:
    container_name: wishlist
    restart: always
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: wishlist
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5555:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: wishlist